Make sure kernel_stat64 struct is defined on 64-bit MIPS
kernel_stat64 is used only on 32-bit architectures, but it needs to be
defined everywhere, otherwise the compilation fails with:

sandbox/linux/syscall_broker/broker_client.cc:193:28: error:
invalid application of ‘sizeof’ to incomplete type ‘sandbox::syscall_broker::kernel_stat64’

Now linux_stat.h is organized as follows: first come definitions of
kernel_stat64 (one for MIPS and one for all other architectures), then
come definitions of kernel_stat for different architectures.

Change-Id: I59bee3b511d124d59b23f2e7a8339ae69736baa5
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3304194
Reviewed-by: Matthew Denton <mpdenton@chromium.org>
Commit-Queue: Matthew Denton <mpdenton@chromium.org>
Cr-Commit-Position: refs/heads/main@{#946312}
NOKEYCHECK=True
GitOrigin-RevId: 2e2070d97040715516b99c79e5e59d7f83aa1d0e