vs2015: fix rename of _crt_va_start
d:\src\cr3\src\sandbox\win\sandbox_poc\main_ui_window.cc(627): error C3861: '_crt_va_start': identifier not found

R=jschuh@chromium.org
BUG=440500

Review URL: https://codereview.chromium.org/1165283003

Cr-Original-Commit-Position: refs/heads/master@{#333389}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 85709cb0b754fd92efe6ea0de2da3b4a875db40f