Revert 208924 "attempt to make the libc urandom override work fo..."
Broke Linux ASAN build:
[1054/1063] LINK nacl_helper
../../chrome/nacl/nacl_helper_linux.cc:229: error: undefined reference to 'sandbox::InitLibcUrandomOverrides()'


> attempt to make the libc urandom override work for non-glibc too
> 
> This patch attempts to generalise the linux libc urandom override, so
> that it works for non-glibc linux platforms too.
> 
> Review URL: https://chromiumcodereview.appspot.com/17066002

TBR=mostynb@opera.com

Review URL: https://codereview.chromium.org/18069003

Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 7790c086f7a606b72b05a1109e4af56a4db4859c