Remove extra semicolon after member function definition
ARM64 Chromium build starts to complain (see below) the extra semicolon
after inline member function definition. The extra semicolon was there in the
initial arm64 support of Chromium sandbox. Seems it is exposed by option
-Wextra-semi which was just enabled in Chromium in https://crrev.com/c/1489102
for Windows.

../../sandbox/win/src/resolver_64.cc(57,4): error: extra ';' after member function definition [-Werror,-Wextra-semi]
  };
   ^
1 error generated.

TBR=wfh

Bug: 893460
Change-Id: I31a9996cad8739a00b5ba1a2ab35b40feb792e79
Reviewed-on: https://chromium-review.googlesource.com/c/1493158
Reviewed-by: Nico Weber <thakis@chromium.org>
Reviewed-by: Bruce Dawson <brucedawson@chromium.org>
Commit-Queue: Nico Weber <thakis@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#636244}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: 9422b15824f55dca757508baa73408b86c6c229f